gems:
  - jekyll-sitemap


speakers:
  - name: Aaron Patterson
    description: Ruby & Rails core team member. Aaron's the most <a href="https://twitter.com/tenderlove" target="_blank">@tenderlove</a>-ing person you'll ever meet. He works at Github.
    image: aaron.png

  - name: Akira Matsuda
    description: CRuby core team. <a href="https://twitter.com/amatsuda" target="_blank">@amatsuda</a>'s also the founder of Asakusa.rb, one of the most active regional Rubyist group in Tokyo, Japan.
    image: akira.png

  - name: Aja Hammerly
    description: An awesome dinosaur that codes in Ruby and does DevOps. <a href="https://twitter.com/the_thagomizer" target="_blank">@the_thagomizer</a>'s a Google Cloud Advocate @ Google.
    image: aja.png

  - name: Tim Riley
    description: <a href="https://twitter.com/timriley" target="_blank">@timriley</a>'s a director & developer at @icelab. He's also one of dry-rb's core developer.
    image: tim.png

  - name: Saron Yitbarek
    description: <a href="https://twitter.com/saronyitbarek" target="_blank">@saronyitbarek</a>'s the founder of CodeNewbie.org, a really supportive community of people learning to code. They produce some cool podcasts weekly. She also co-hosts @rubybookclub.
    image: saron.jpg

  - name: Konstantin Haase
    description: Founder and CTO of Travis CI, <a href="https://twitter.com/konstantinhaase" target="_blank">@konstantinhaase</a>'s a one of a kind speaker that often blows our minds with his presentations. He's also the main contributor of Sinatra.
    image: konstantin.jpg
